language: python
python:
- '3.6'
services:
- docker
install:
- pip install -r requirements.txt
script:
- pylint app/app
before_deploy:
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
- sudo apt-get install apt-transport-https
- sudo apt-get update && sudo apt-get install azure-cli
deploy:
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^dev|master$
  provider: script
  script: scripts/publish && scripts/deploy
  