language: python
python:
- '3.6'
services:
- docker
install:
- pip install -r requirements.txt
script:
- pylint app
- scripts/publish $TRAVIS_TAG
env:
  global:
  - secure: kuePXDwDhzCaVJfRe3OfJvuMUCScggW4rHCZLt5MWRj4ikbnqZJrSTwHAYcA6zefSfPqzLJ9bRMq2Pcv8lmapcxylD7Mf7X3AxkEbQqM+ouNn+yJBYJYcKwlgebmbm/IVU7z3HrWWpXHQUgcpWgaH1TJUvqGeT5dnABG9FMyYTY97RCDJvDd+FjsD4OonI1pp66hjmDGJN3CchjtJYFt4wYSYt37Sx+U8TGbct2E6URAVNFaK63lSICKJaS7VFkGKMp/y/epv3Z+jY/qFHCsZYb3XyVonV5obP+9eJtaDbZSLNFtkcR0ZW3Barm5C/Yb7gSYbaicWdyNuUiqxYgp41HcXLYjLFcTtUpDS3FRQA2T5zari5JduoM6/r6Rd/0EPgjDTWTV3gzwCsplX3H4yuelRwsLhBNfz/CxM1zyGnkshZzdmHDl8ZSCoW9v9Lh8hi/EZ+fpJdwlaiojNme3UzwPjCEOF9GLM6DS5IH6PFYKOXVgyXwuSulfbDbHdYGBH5+6hGI4PFWKAUlqXFRQa63Je+wWE9t6Cc+i1tunHaivkJJ6oYz8eLjdx2UaLjK65R84mwUDCGhwykdkWe6/zykflMzX+IfaPOihoaiyrbv6r0ZbSSja9viKPoMfMfbXvWwKfoD16vKV3PKRqqTDARzKPHNGe0XU02l/dLVc670=
  - secure: U7eNBV01u46gfZxmSAWl1RpA62xgSZzMba6uFrje7cFx+pGNkonadqm0pbtYkpWZDaqWvqC01LG6Scig3iFYz98EfQTjD7OWRmgVFeOdHw99gM5JXx3Nj5NO/fkd5FbanVdzRZjZelXzcyIx+5U4DOkvg/vqM+gA5yGumTDggyHq/9L1UXdTuuDesKlvuRYeSNGU+NdXp1Qf3y4oVn1HDfHWQcXJQ1mON7xl/Pe+mkPY55Jv5ZMnnRFPhPz4duEHvKgWe5UaLMqqfgOpGM87xwJ8VPQD5V3gjpA3l0FxZCu/eLpovWnoUvgGhQoe+56OjFiHwxUG+LXkJYe4zjTwMJVPqtNPz5AsSIEq3xullUmq8G/YKq48lV7vNMTY8msgiJb39SrpLpCrEZmuEcb/bBPCaP/LUbeDl16OlN6kei6bsH6mkU4XvcU5y647LwRFmd8JSgGFzT/Iedsi+cPfwWNqSC7fY+PT6TifpbyClmYjS2GyE3ZZ6eNYzua2D3crUl4TZdA2xBlZ0Pn/0jQRActqL2XyPtLIKm5Exgto+PidQsgoMaHSjDgHtryE63so8lsuKBdY7wk9ewotTVIP1iE4UqOfaFHQsdUQw+ksYHBsx0vso5Jf3QMYjyVP2Vp2mc2R9Tugo7N+U8lRr6+ICDqpIntVqr1gBZJ4EYGWPYA=
